[package]
name = "rhythm"
version = "0.1.0"
authors = ["pseudoscalar"]
edition = "2018"

[dependencies]
rodio = "0.8.1"
sdl2 = "0.32.1"
specs = "0.14.3"

[replace]
"rodio:0.8.1" = { path = '../rodio' }
